### PR TITLE
Add Discord Rich Presence and an option to disable it

### PR DESCRIPTION
**Pull request by pythonmcpi**
- [x] Discord Rich Presence
- [x] An option to disable it
- [ ] ~~Discord game invites / join games via rich presence~~

### CODE REVIEW

**Comment by nonperforming** [comment]
This would work well with Steam Rich Presence as well, since it (the game) is now on Steam.

**Comment by pythonmcpi** [comment]
For anyone interested in this PR: Feel free to take over and fix the merge conflicts. I don't really like how past me implemented rich presence, so it might be easier to rewrite the whole thing instead.

I don't use desktop discord anymore, so I'm unable to test any changes. I have no plans to update this PR.

**Comment by dabigf5** [comment]
RIP rich presence pull request
2021-2024

you will be missed

**Comment by nonperforming** [comment]
o7

**Comment by pythoncoder1234** [comment]
rip

**Pull request closed without merging**
