### PR TITLE
TanksON isn't Json, but TanksJson is!

### PR DESCRIPTION
**Pull request by ghostlypi**
Replace TanksON with TanksJson

### CODE REVIEW

**Comment by dabigf5** [comment]
imo "Tanks Object Notation" rolls off the tongue better than "Tanks JavaScript Object Notation"

**Comment by aehmttw** [comment]
rip pom pom

**Comment by ghostlypi** [comment]
1) TankON had it's own JSON parser which is not good, given the scope of where TanksON will be used.
2) TanksJson is not meant to be backwards compatible with TanksON, but TanksON has not been rolled out in a release, so this should not be an issue.
3) Theoretically the only changes to the pom are upgrades to the LWJGL versions and adding org.json for json parsing. Ping me on discord with the error message and I can try to help. "It builds on my Machines"

**Comment by dabigf5** [comment]
TanksON is not exactly json, it's more like a format inspired by it, custom parser is better in that regard because we can make syntactical extensions to it without rewriting the json standard (and I think some actually have already been made)

**Comment by ghostlypi** [comment]
3) The POM has been "fixed", I think maven wanted some properties which were missing before.
3b) Github CodeQL is not exactly a clean environment, but nonetheless, I did create the pom.xml and therefore should do a better job of making sure the QL passes. That will be a project I take on in the near future probably.

Notes about TanksON versus JSON:
TanksON is not JSON, but it was intended to very closely follow JSON. There are a lot of differences between the 2 parsers, however most of them do not truly matter for actual tanks files. The lack of support for infinity and -infinity is definitely one of the issues, however such values tend to cause other issues beyond just being saved. A bullet with +inf knockback will literally cause the game to crash (or with some of the newer commits create some very unhappy faces). This is not optimal from a gameplay standpoint and while such error maybe interesting once or twice, it's just not a good gameplay feature to have unspecified behavior.

Notes on the lettered versions of Tanks:
1.6.a that you build locally isn't even a beta build of tanks. It is a) not remotely stable and  b) it's missing features for the 1.6 update. The builds system should change soon to better demarcate betas, however you should not bank on any non-release version being forwards/backwards compatible.

**Comment by ghostlypi** [comment]
Closing Pull Request due to Architectural Issues.

**Pull request closed without merging**
