### PR TITLE
modapi feature merge: editor selectors

### PR DESCRIPTION
**Pull request by pythoncoder1234**
- Properties such as beat pattern and tank teams are now modular and easily customizable
- Lot of changes under the hood, but not much has changed on the surface
- Also a bunch of editor improvements, more on that later (most don't work yet because an obstacle grid is needed)
- Uses code from modapi, which has not seen any bugs in a few months to years

### CODE REVIEW

**Comment by pythoncoder1234** [comment]
everything is kinda interdependent, which is why there's so many changes

**Comment by aehmttw** [comment]
A few things:

The color/shield indicator on the teams list is gone
Screen Shot 2024-11-30 at 4 00 32 PM

For some reason, the team select and rotate tank buttons show up in select mode - is this intentional? Those buttons would only show in build mode before because they were only relevant to that mode.


Screen Shot 2024-11-30 at 4 01 33 PM

**Comment by pythoncoder1234** [comment]
1. Hmm, was that always there? Never noticed it. I can implement that.
2. Yes, the idea is that changing the rotations would change any tanks in the selection, likewise changing stack height would change the stack height of any obstacles in the selection. I'll do this later as there is no obstacle grid yet.

**Comment by aehmttw** [comment]
I fixed the bugs. It also turns out you removed the ability to add or delete teams so I added that back.

PS. Why did you make the button's selected field get set AFTER checking whether it was clicked instead of before? This kind of caused some problems lmao

**Pull request merged**
